# project definitions
project: communote
audience: users, developers, admins
version: all
output: web
homepage_title: Communote
site_title: Communote
project_folder: doc
github_editme_path: Communote/communote.github.io
disqus_shortname: communote-doc

pdf_file_name: Communote-Documentation.pdf
pdf_rest_api_file_name: REST-API-Documentation.pdf

port: 4009

exclude:
  - _site
  - _drafts
  - configs/

# same for all
host: 127.0.0.1
feedback_email: github@communote.com

highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true
  parse_block_html: true

collections:
  tooltips:
    output: false

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      comments: true
      search: true
  -
    scope:
      path: ""
      type: "tooltips"
    values:
      layout: "page"
      comments: true
      search: true
      tooltip: true
